# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IkuO8Odm3m_Hpx_uMNJ9-qqqYWaGyOuC
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("pranaykoppula/torgo-audio")

print("Path to dataset files:", path)

# Commented out IPython magic to ensure Python compatibility.
# %ls /kaggle/input/torgo-audio

# Commented out IPython magic to ensure Python compatibility.
# %ls /root/.cache/kagglehub/datasets/pranaykoppula/torgo-audio/versions/1/F_Con

!pip install denoiser
!pip install voicefixer

import os
import random
from pathlib import Path
import json

# Root dataset path
DATA_ROOT = Path("/kaggle/input/torgo-audio")

# Fixed seed for reproducibility
SEED = 42
random.seed(SEED)

# Subset folders
subsets = {
    "F_Con": ["FC01S01", "FC02S02"],
    "F_Dys": ["F01", "F03S01"],
    "M_Con": ["MC01S01", "MC01S02"],
    "M_Dys": ["M01S01", "M01S02"],
}

train_files = []
test_files = []

for label, speakers in subsets.items():
    for speaker in speakers:
        speaker_path = DATA_ROOT / label / f"wav_arrayMic_{speaker}"
        print(speaker_path)

        # Get only .wav files and sort for determinism
        files = sorted([f for f in speaker_path.glob("*.wav")])

        # Use ONLY first 50 files
        files = files[:50]

        # Shuffle with fixed seed
        random.shuffle(files)

        # 80/20 split
        N = len(files)
        N_train = int(0.8 * N)

        train_split = files[:N_train]
        test_split = files[N_train:]

        # Store with label
        train_files += [(str(f), label) for f in train_split]
        test_files += [(str(f), label) for f in test_split]

print(f"Train samples: {len(train_files)}")
print(f"Test samples: {len(test_files)}")

"""# Clean Speech Classification"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss, correct, total = 0, 0, 0

    for x, y in loader:
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * x.size(0)
        preds = out.argmax(1)
        correct += (preds == y).sum().item()
        total += y.size(0)

    return total_loss / total, correct / total

@torch.no_grad()
def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss, correct, total = 0, 0, 0
    all_preds, all_labels = [], []

    for x, y in loader:
        x, y = x.to(device), y.to(device)

        out = model(x)
        loss = criterion(out, y)

        total_loss += loss.item() * x.size(0)
        preds = out.argmax(1)

        correct += (preds == y).sum().item()
        total += y.size(0)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(y.cpu().numpy())

    return (
        total_loss / total,
        correct / total,
        np.array(all_preds),
        np.array(all_labels),
    )

def train_model(model, train_loader, val_loader, epochs=20, lr=1e-3, device="cuda"):
    model = model.to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    history = {
        "train_loss": [],
        "train_acc": [],
        "val_loss": [],
        "val_acc": [],
    }

    for epoch in range(epochs):
        tr_loss, tr_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc, _, _ = evaluate(model, val_loader, criterion, device)

        history["train_loss"].append(tr_loss)
        history["train_acc"].append(tr_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        print(f"Epoch {epoch+1:02d} | "
              f"Train Loss {tr_loss:.4f} Acc {tr_acc:.3f} | "
              f"Val Loss {val_loss:.4f} Acc {val_acc:.3f}")

    return model, history

def plot_history(history, title="Training curves"):
    epochs = range(1, len(history["train_loss"]) + 1)

    plt.figure()
    plt.plot(epochs, history["train_loss"], label="Train Loss")
    plt.plot(epochs, history["val_loss"], label="Val Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title(title + " - Loss")
    plt.legend()
    plt.show()

    plt.figure()
    plt.plot(epochs, history["train_acc"], label="Train Acc")
    plt.plot(epochs, history["val_acc"], label="Val Acc")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.title(title + " - Accuracy")
    plt.legend()
    plt.show()

def plot_confusion(y_true, y_pred, class_names=("Control", "Dysarthric"), title=""):
    cm = confusion_matrix(y_true, y_pred)

    disp = ConfusionMatrixDisplay(cm, display_labels=class_names)
    disp.plot()

    # Use the 'title' argument here
    plt.title("Confusion Matrix"+title)
    plt.show()

    print("\nClassification Report:\n")
    print(classification_report(y_true, y_pred, target_names=class_names))

def run_experiment(model_class, train_dataset, test_dataset, batch_size=16, epochs=20, lr=1e-3, device="cuda"):
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size)

    model = model_class()

    model, history = train_model(model, train_loader, test_loader, epochs, lr, device)

    plot_history(history, title=model_class.__name__)

    # Final evaluation for confusion matrix
    _, _, preds, labels = evaluate(model, test_loader, nn.CrossEntropyLoss(), device)
    plot_confusion(labels, preds)

    return model, history

class NonLinearModel(nn.Module):
    def __init__(self, num_feats=257):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(num_feats, num_feats//2),
            nn.ReLU(),
            nn.Linear(num_feats//2, 2)
        )

    def forward(self, x):
        x = x.mean(-1)
        return self.net(x)

class ConvModel(nn.Module):
    def __init__(self, num_feats=64):  # ⭐ changed from 257 → 64
        super().__init__()

        self.net = nn.Sequential(
            nn.Conv1d(num_feats, 128, kernel_size=7, stride=2, padding=3),
            nn.ReLU(),
            nn.Conv1d(128, 2, kernel_size=5, stride=2, padding=2),
        )

    def forward(self, x):
        x = self.net(x)      # (B, 2, T')
        return x.mean(-1)    # global average over time


class LSTMModel(nn.Module):
    def __init__(self, num_feats=64, hidden=32):  # ⭐ 257 → 64
        super().__init__()

        self.lstm = nn.LSTM(
            input_size=num_feats,
            hidden_size=hidden,
            batch_first=True,
            bidirectional=True
        )

        self.fc = nn.Linear(hidden * 2, 2)

    def forward(self, x):
        x = x.permute(0, 2, 1)   # (B, T, F)

        _, (h, _) = self.lstm(x)

        h = torch.cat([h[-2], h[-1]], dim=1)  # (B, 2H)

        return self.fc(h)

import torch
import torchaudio
import torchaudio.transforms as T

SAMPLE_RATE = 16000

# ---- STFT magnitude (257 freq bins) ----
stft_transform = T.Spectrogram(
    n_fft=512,          # -> 257 freq bins
    hop_length=160,
    power=2.0
)

# ---- Log-Mel spectrogram ----
mel_transform = T.MelSpectrogram(
    sample_rate=SAMPLE_RATE,
    n_fft=512,
    hop_length=160,
    n_mels=64
)

db_transform = T.AmplitudeToDB()

from torch.utils.data import Dataset

LABEL_MAP = {
    "F_Con": 0,
    "M_Con": 0,
    "F_Dys": 1,
    "M_Dys": 1,
}


class TorgoDataset(Dataset):
    def __init__(self, file_list, feature_type="stft"):
        """
        feature_type:
            "stft" -> for NonLinearModel
            "mel"  -> for ConvModel / LSTMModel
        """
        self.file_list = file_list
        self.feature_type = feature_type

    def __len__(self):
        return len(self.file_list)

    def _load_audio(self, path):
        wav, sr = torchaudio.load(path)

        # mono
        if wav.shape[0] > 1:
            wav = wav.mean(dim=0, keepdim=True)

        # resample
        if sr != SAMPLE_RATE:
            wav = torchaudio.functional.resample(wav, sr, SAMPLE_RATE)

        return wav

    def _extract_features(self, wav):
        if self.feature_type == "stft":
            spec = stft_transform(wav)        # (1, 257, T)
            return spec.squeeze(0)            # (257, T)

        elif self.feature_type == "mel":
            mel = mel_transform(wav)
            mel_db = db_transform(mel)
            return mel_db.squeeze(0)          # (n_mels, T)

        else:
            raise ValueError("Unknown feature_type")

    def __getitem__(self, idx):
        path, label = self.file_list[idx]

        wav = self._load_audio(path)
        feats = self._extract_features(wav)

        return feats, LABEL_MAP[label]


def pad_collate(batch):
    """
    Pads variable-length spectrograms in time dimension.
    Input:
        batch = [(feat, label), ...]
        feat shape = (F, T)
    Output:
        feats -> (B, F, T_max)
        labels -> (B,)
    """
    feats, labels = zip(*batch)

    # Find max time length in batch
    max_len = max(f.shape[1] for f in feats)

    padded_feats = []
    for f in feats:
        pad_size = max_len - f.shape[1]
        f_padded = F.pad(f, (0, pad_size))  # pad time dimension
        padded_feats.append(f_padded)

    feats_tensor = torch.stack(padded_feats)
    labels_tensor = torch.tensor(labels)

    return feats_tensor, labels_tensor

def create_dataloaders(train_files, test_files, feature_type, batch_size=16):
    train_ds = TorgoDataset(train_files, feature_type)
    test_ds = TorgoDataset(test_files, feature_type)

    train_loader = DataLoader(
        train_ds,
        batch_size=batch_size,
        shuffle=True,
        collate_fn=pad_collate   # ⭐ key fix
    )

    test_loader = DataLoader(
        test_ds,
        batch_size=batch_size,
        collate_fn=pad_collate   # ⭐ key fix
    )

    return train_loader, test_loader

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
import torch.nn.functional as F


@torch.no_grad()
def plot_roc_auc(model, loader, device="cuda", title="ROC Curve"):
    model.eval()

    probs_list = []
    labels_list = []

    for x, y in loader:
        x = x.to(device)

        logits = model(x)
        probs = F.softmax(logits, dim=1)[:, 1]  # probability of Dysarthric

        probs_list.extend(probs.cpu().numpy())
        labels_list.extend(y.numpy())

    fpr, tpr, _ = roc_curve(labels_list, probs_list)
    roc_auc = auc(fpr, tpr)

    plt.figure()
    plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
    plt.plot([0, 1], [0, 1], linestyle="--")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(title)
    plt.legend()
    plt.show()

    return roc_auc

device = "cuda"
train_loader, test_loader = create_dataloaders(train_files, test_files, "stft")

model, history = train_model(NonLinearModel(), train_loader, test_loader, device=device)

plot_history(history, "NonLinearModel")
_, _, preds, labels = evaluate(model, test_loader, nn.CrossEntropyLoss(), device)
plot_confusion(labels, preds)

plot_roc_auc(model, test_loader, device, "NonLinearModel ROC")

train_loader, test_loader = create_dataloaders(train_files, test_files, "mel")

model, history = train_model(ConvModel(), train_loader, test_loader, device=device)
plot_history(history, "ConvModel")
_, _, preds, labels = evaluate(model, test_loader, nn.CrossEntropyLoss(), device)
plot_confusion(labels, preds)
plot_roc_auc(model, test_loader, device, "ConvModel ROC")

train_loader, test_loader = create_dataloaders(train_files, test_files, "mel")

model, history = train_model(LSTMModel(), train_loader, test_loader, device=device)
plot_history(history, "LSTMModel")
_, _, preds, labels = evaluate(model, test_loader, nn.CrossEntropyLoss(), device)
plot_confusion(labels, preds)
plot_roc_auc(model, test_loader, device, "LSTMModel ROC")

"""# Denoised training"""

!unzip Noises\&RIR.zip

# Commented out IPython magic to ensure Python compatibility.
# %ls /content/Noises&RIR

from pathlib import Path
import torchaudio
import torch

NOISE_ROOT = Path("/content/Noises&RIR")
NOISE_DIR = NOISE_ROOT / "Noises"
print(NOISE_DIR)
def load_noises(sample_rate=16000):
    noise_paths = sorted(NOISE_DIR.glob("*.wav"))
    noises = {}

    for p in noise_paths:
        wav, sr = torchaudio.load(p)

        if wav.shape[0] > 1:
            wav = wav.mean(0, keepdim=True)

        if sr != sample_rate:
            wav = torchaudio.functional.resample(wav, sr, sample_rate)

        noises[p.stem] = wav.squeeze(0)

    return noises


noises = load_noises()
print("Loaded noises:", list(noises.keys()))

def add_noise(clean, noise, snr_db):
    """
    clean: (T,)
    noise: (T,) or shorter
    """

    if noise.numel() < clean.numel():
        repeat = clean.numel() // noise.numel() + 1
        noise = noise.repeat(repeat)

    noise = noise[: clean.numel()]

    clean_power = clean.pow(2).mean()
    noise_power = noise.pow(2).mean()

    snr_linear = 10 ** (snr_db / 10)

    scale = torch.sqrt(clean_power / (snr_linear * noise_power))
    noisy = clean + scale * noise

    return noisy

def spectral_subtraction(noisy, sr=16000):
    spec = torch.stft(noisy, n_fft=512, hop_length=160, return_complex=True)
    mag, phase = spec.abs(), spec.angle()

    noise_est = mag[:, :10].mean(dim=1, keepdim=True)  # noise from first frames
    clean_mag = torch.clamp(mag - noise_est, min=0.0)

    clean_spec = clean_mag * torch.exp(1j * phase)
    clean = torch.istft(clean_spec, n_fft=512, hop_length=160)

    return clean

def wiener_filter(noisy):
    spec = torch.stft(noisy, n_fft=512, hop_length=160, return_complex=True)
    mag, phase = spec.abs(), spec.angle()

    noise_est = mag[:, :10].mean(dim=1, keepdim=True)
    gain = mag.pow(2) / (mag.pow(2) + noise_est.pow(2))

    clean_mag = gain * mag
    clean_spec = clean_mag * torch.exp(1j * phase)

    clean = torch.istft(clean_spec, n_fft=512, hop_length=160)
    return clean

def mmse_denoise(noisy):
    spec = torch.stft(noisy, n_fft=512, hop_length=160, return_complex=True)
    mag, phase = spec.abs(), spec.angle()

    noise_est = mag[:, :10].mean(dim=1, keepdim=True)
    snr = mag.pow(2) / (noise_est.pow(2) + 1e-8)

    gain = snr / (1 + snr)
    clean_mag = gain * mag

    clean_spec = clean_mag * torch.exp(1j * phase)
    clean = torch.istft(clean_spec, n_fft=512, hop_length=160)

    return clean

def facebook_denoise(wav):
    try:
        from denoiser import pretrained
        model = pretrained.dns64().cuda().eval()
        with torch.no_grad():
            return model(wav.unsqueeze(0).cuda()).cpu().squeeze()
    except:
        print("fuuuuuuuuuuuuuuuuck")
        return wav  # fallback

def voicefixer_denoise(wav):
    try:
        from voicefixer import VoiceFixer
        vf = VoiceFixer()
        return vf.restore_inmem(wav.unsqueeze(0), cuda=False).squeeze(0)
    except:
        print("fuuuuuuuuuuuuuuuuck")
        return wav

class NoisyTorgoDataset(TorgoDataset):
    def __init__(self, file_list, feature_type, noise=None, snr=None, denoise_fn=None):
        super().__init__(file_list, feature_type)

        self.noise = noise
        self.snr = snr
        self.denoise_fn = denoise_fn

    def __getitem__(self, idx):
        path, label = self.file_list[idx]

        wav = self._load_audio(path).squeeze(0)

        # ---- add noise ----
        if self.noise is not None and self.snr is not None:
            wav = add_noise(wav, self.noise, self.snr)

        # ---- denoise ----
        if self.denoise_fn is not None:
            wav = self.denoise_fn(wav)

        feats = self._extract_features(wav.unsqueeze(0))

        return feats, LABEL_MAP[label]

def run_full_experiment(train_files, test_files, device="cuda"):
    snrs = [-10, -5, 0]

    denoisers = {
        "specsub": spectral_subtraction,
        "wiener": wiener_filter,
        "mmse": mmse_denoise,
        "facebook": facebook_denoise,
        "voicefixer": voicefixer_denoise,
    }

    models = {
        "linear": (NonLinearModel, "stft", 257),
        "conv": (ConvModel, "mel", 64),
        "lstm": (LSTMModel, "mel", 64),
    }

    results = []

    for noise_name, noise_wav in noises.items():
        for snr in snrs:
            for den_name, den_fn in denoisers.items():
                print(f"\nNoise={noise_name} | SNR={snr} | Denoise={den_name}")

                for model_name, (Model, feat, nf) in models.items():
                    conf = f"_{noise_name}_{snr}db_{den_name}_{model_name}"
                    print(conf)
                    train_ds = NoisyTorgoDataset(train_files, feat, noise_wav, snr, den_fn)
                    test_ds = NoisyTorgoDataset(test_files, feat, noise_wav, snr, den_fn)

                    train_loader = DataLoader(train_ds, batch_size=64, shuffle=True, collate_fn=pad_collate)
                    test_loader = DataLoader(test_ds, batch_size=64, collate_fn=pad_collate)

                    model, _ = train_model(Model(nf), train_loader, test_loader, device=device , epochs=8)

                    _, acc, preds, labels = evaluate(model, test_loader, nn.CrossEntropyLoss(), device)
                    plot_confusion(labels, preds , title=conf)
                    results.append({
                        "noise": noise_name,
                        "snr": snr,
                        "denoise": den_name,
                        "model": model_name,
                        "accuracy": acc,
                    })

    return results

import pandas as pd

results = run_full_experiment(train_files, test_files, device=device)

df = pd.DataFrame(results)
df.to_csv("denoise_results.csv", index=False)

print(df.head())

