# -*- coding: utf-8 -*-
"""lp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wdAqrTb3UYgihhvSU2ISII6aChspqXWG
"""

url = "https://drive.google.com/file/d/13b0EEoFVdecVVzY-E2PszN1FxVekOsCU/view?usp=sharing"
import gdown

file_id = "13b0EEoFVdecVVzY-E2PszN1FxVekOsCU"
url = f"https://drive.google.com/uc?id={file_id}"
output_zip = "file.tar.gz"

# Download
gdown.download(url, output_zip, quiet=False)

!tar -xvzf /content/file.tar.gz

"""# 5.a"""

# Apply LP of order N on each STFT frame (25ms window, 10ms shift, Hamming window)

import numpy as np
import scipy.io.wavfile as wav
from scipy.signal.windows import hamming
from scipy.signal import lfilter
from scipy.linalg import toeplitz
import matplotlib.pyplot as plt

def load_audio(file_loc:str):
  sample_rate, audio = wav.read(file_loc)
  audio = audio.astype(np.float64)

  # Normalize audio
  audio = audio / np.max(np.abs(audio))

  print(f"Sample Rate: {sample_rate} Hz")
  print(f"Audio Length: {len(audio)} samples ({len(audio)/sample_rate:.3f} seconds)")

  return sample_rate , audio
sample_rate , audio = load_audio("dataFiles/Train_0_Example_1.wav")

# STFT Parameters
window_duration = 0.025  # 25 ms
hop_duration = 0.010     # 10 ms shift

def get_window(sample_rate , audio):
  window_length = int(window_duration * sample_rate)
  hop_length = int(hop_duration * sample_rate)

  print(f"Window Length: {window_length} samples ({window_duration*1000} ms)")
  print(f"Hop Length: {hop_length} samples ({hop_duration*1000} ms)")

  # Create Hamming window
  window = hamming(window_length)

  # Calculate number of frames
  num_frames = (len(audio) - window_length) // hop_length + 1
  print(f"Number of Frames: {num_frames}")
  return num_frames , window_length , hop_length ,window

num_frames , window_length , hop_length , window = get_window(sample_rate , audio)

def compute_lp_coefficients(frame, order):
    """
    Levinson-Durbin algorithm
    """
    # Compute autocorrelation
    r = np.correlate(frame, frame, mode='full')
    r = r[len(frame)-1:]

    r = r[:order+1]

    # R * a = r where R is Toeplitz matrix of r[0:order] and we solve for a[1:order+1]
    if r[0] == 0:
        return np.zeros(order), 0

    r = r / r[0]

    R = toeplitz(r[:order])
    a = np.linalg.solve(R, -r[1:order+1])

    return a, r[0]

def compute_residual_energy(frame, lp_coeffs):
    """
    Residual e[n] = x[n] - sum(a[k] * x[n-k]) for k=1 to p
    """
    a = np.concatenate([[1], lp_coeffs])
    residual = lfilter(a, [1], frame)

    energy = np.sum(residual**2)

    return energy, residual

def compute_audio_residual(num_frames , window_length , hop_length , window):
  lp_orders = [4, 12]

  residual_energies = {order: [] for order in lp_orders}
  frame_energies = []

  for i in range(num_frames):
      start = i * hop_length
      end = start + window_length
      frame = audio[start:end] * window

      # for reference Compute frame energy
      frame_energies.append(np.sum(frame**2))

      # Compute LP and residual energy for each order
      for order in lp_orders:
          lp_coeffs, _ = compute_lp_coefficients(frame, order)
          energy, _ = compute_residual_energy(frame, lp_coeffs)
          residual_energies[order].append(energy)

  frame_energies = np.array(frame_energies)
  for order in lp_orders:
      residual_energies[order] = np.array(residual_energies[order])
  return lp_orders , residual_energies, frame_energies

lp_orders , residual_energies, frame_energies = compute_audio_residual(num_frames , window_length , hop_length , window)

def plot(lp_orders , residual_energies, frame_energies, f):
  frame_times = np.arange(num_frames) * hop_duration

  fig, axes = plt.subplots(3, 1, figsize=(14, 10))

  time_audio = np.arange(len(audio)) / sample_rate
  axes[0].plot(time_audio, audio, 'b-', linewidth=0.5)
  axes[0].set_xlabel('Time (s)')
  axes[0].set_ylabel('Amplitude')
  axes[0].set_title(f'Original Audio Waveform - {f}')
  axes[0].grid(True, alpha=0.3)

  # residual energies for different orders
  colors = plt.cm.viridis(np.linspace(0.8, 1, len(lp_orders)))
  for idx, order in enumerate(lp_orders):
      axes[1].plot(frame_times, 10*np.log10(residual_energies[order] + 1e-10),
                  label=f'Order N={order}', color=colors[idx], linewidth=1.2)

  axes[1].set_xlabel('Time (s)')
  axes[1].set_ylabel('Residual Energy (dB)')
  axes[1].set_title(f'Residual Energy vs Frame for Different LP Orders {f}')
  axes[1].legend(loc='upper right')
  axes[1].grid(True, alpha=0.3)

  # Plot frame energy and residual energy (for order=12)
  axes[2].plot(frame_times, 10*np.log10(frame_energies + 1e-10),
              'b-', label='Frame Energy', linewidth=1.2, alpha=0.7)
  axes[2].plot(frame_times, 10*np.log10(residual_energies[12] + 1e-10),
              'r-', label='Residual Energy (N=12)', linewidth=1.2, alpha=0.7)
  axes[2].set_xlabel('Time (s)')
  axes[2].set_ylabel('Energy (dB)')
  axes[2].set_title(f'Comparison: Frame Energy vs Residual Energy (LP Order=12) , {f}')
  axes[2].legend(loc='upper right')
  axes[2].grid(True, alpha=0.3)

  plt.tight_layout()
  plt.savefig('residual_energy_plot.png', dpi=150, bbox_inches='tight')
  plt.show()

plot(lp_orders , residual_energies, frame_energies , "")

def plot_g(audio , frame_energies , f):

  # Gain: G = 10*log10(Frame Energy / Residual Energy) . Higher prediction gain indicates more predictable signal (voiced speech)

  fig, axes = plt.subplots(2, 1, figsize=(14, 8))
  time_audio = np.arange(len(audio)) / sample_rate
  frame_times = np.arange(num_frames) * hop_duration
  colors = plt.cm.viridis(np.linspace(0.8, 1, len(lp_orders)))
  # Plot original waveform
  axes[0].plot(time_audio, audio, 'b-', linewidth=0.5)
  axes[0].set_xlabel('Time (s)')
  axes[0].set_ylabel('Amplitude')
  axes[0].set_title(f'Original Audio Waveform {f}')
  axes[0].grid(True, alpha=0.3)

  for idx, order in enumerate(lp_orders):
      prediction_gain = 10 * np.log10((frame_energies + 1e-10) / (residual_energies[order] + 1e-10))
      axes[1].plot(frame_times, prediction_gain,
                  label=f'Order N={order}', color=colors[idx], linewidth=1.2)

  axes[1].set_xlabel('Time (s)')
  axes[1].set_ylabel('Prediction Gain (dB)')
  axes[1].set_title(f'Prediction Gain vs Frame for Different LP Orders {f}')
  axes[1].legend(loc='upper right')
  axes[1].grid(True, alpha=0.3)

  plt.tight_layout()
  plt.savefig('prediction_gain_plot.png', dpi=150, bbox_inches='tight')
  plt.show()

  print("\n=== Prediction Gain Statistics (dB) ===")
  for order in lp_orders:
      prediction_gain = 10 * np.log10((frame_energies + 1e-10) / (residual_energies[order] + 1e-10))
      print(f"Order N={order}: Mean={np.mean(prediction_gain):.2f}, Max={np.max(prediction_gain):.2f}, Min={np.min(prediction_gain):.2f}")

plot_g(audio , frame_energies , "")

import os
for f in os.listdir("/content/dataFiles"):
  sample_rate , audio = load_audio(f"dataFiles/{f}")
  num_frames , window_length , hop_length , window = get_window(sample_rate , audio)
  lp_orders , residual_energies, frame_energies = compute_audio_residual(num_frames , window_length , hop_length , window)
  plot(lp_orders , residual_energies, frame_energies , f)
  plot_g(audio , frame_energies , f)

"""# 5.b"""



