# -*- coding: utf-8 -*-
"""lp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wdAqrTb3UYgihhvSU2ISII6aChspqXWG
"""

url = "https://drive.google.com/file/d/13b0EEoFVdecVVzY-E2PszN1FxVekOsCU/view?usp=sharing"
import gdown

file_id = "13b0EEoFVdecVVzY-E2PszN1FxVekOsCU"
url = f"https://drive.google.com/uc?id={file_id}"
output_zip = "file.tar.gz"

# Download
gdown.download(url, output_zip, quiet=False)

!tar -xvzf /content/file.tar.gz

"""# 5.a"""

# Apply LP of order N on each STFT frame (25ms window, 10ms shift, Hamming window)

import numpy as np
import scipy.io.wavfile as wav
from scipy.signal.windows import hamming
from scipy.signal import lfilter
from scipy.linalg import toeplitz
import matplotlib.pyplot as plt

def load_audio(file_loc:str):
  sample_rate, audio = wav.read(file_loc)
  audio = audio.astype(np.float64)

  # Normalize audio
  audio = audio / np.max(np.abs(audio))

  print(f"Sample Rate: {sample_rate} Hz")
  print(f"Audio Length: {len(audio)} samples ({len(audio)/sample_rate:.3f} seconds)")

  return sample_rate , audio
sample_rate , audio = load_audio("dataFiles/Train_0_Example_1.wav")

# STFT Parameters
window_duration = 0.025  # 25 ms
hop_duration = 0.010     # 10 ms shift

def get_window(sample_rate , audio):
  window_length = int(window_duration * sample_rate)
  hop_length = int(hop_duration * sample_rate)

  print(f"Window Length: {window_length} samples ({window_duration*1000} ms)")
  print(f"Hop Length: {hop_length} samples ({hop_duration*1000} ms)")

  # Create Hamming window
  window = hamming(window_length)

  # Calculate number of frames
  num_frames = (len(audio) - window_length) // hop_length + 1
  print(f"Number of Frames: {num_frames}")
  return num_frames , window_length , hop_length ,window

num_frames , window_length , hop_length , window = get_window(sample_rate , audio)

def compute_lp_coefficients(frame, order):
    """
    Levinson-Durbin algorithm
    """
    # Compute autocorrelation
    r = np.correlate(frame, frame, mode='full')
    r = r[len(frame)-1:]

    r = r[:order+1]

    # R * a = r where R is Toeplitz matrix of r[0:order] and we solve for a[1:order+1]
    if r[0] == 0:
        return np.zeros(order), 0

    r = r / r[0]

    R = toeplitz(r[:order])
    a = np.linalg.solve(R, -r[1:order+1])

    return a, r[0]

def compute_residual_energy(frame, lp_coeffs):
    """
    Residual e[n] = x[n] - sum(a[k] * x[n-k]) for k=1 to p
    """
    a = np.concatenate([[1], lp_coeffs])
    residual = lfilter(a, [1], frame)

    energy = np.sum(residual**2)

    return energy, residual

def compute_audio_residual(num_frames , window_length , hop_length , window):
  lp_orders = [4, 12]

  residual_energies = {order: [] for order in lp_orders}
  frame_energies = []

  for i in range(num_frames):
      start = i * hop_length
      end = start + window_length
      frame = audio[start:end] * window

      # for reference Compute frame energy
      frame_energies.append(np.sum(frame**2))

      # Compute LP and residual energy for each order
      for order in lp_orders:
          lp_coeffs, _ = compute_lp_coefficients(frame, order)
          energy, _ = compute_residual_energy(frame, lp_coeffs)
          residual_energies[order].append(energy)

  frame_energies = np.array(frame_energies)
  for order in lp_orders:
      residual_energies[order] = np.array(residual_energies[order])
  return lp_orders , residual_energies, frame_energies

lp_orders , residual_energies, frame_energies = compute_audio_residual(num_frames , window_length , hop_length , window)

def plot(lp_orders , residual_energies, frame_energies, f):
  frame_times = np.arange(num_frames) * hop_duration

  fig, axes = plt.subplots(3, 1, figsize=(14, 10))

  time_audio = np.arange(len(audio)) / sample_rate
  axes[0].plot(time_audio, audio, 'b-', linewidth=0.5)
  axes[0].set_xlabel('Time (s)')
  axes[0].set_ylabel('Amplitude')
  axes[0].set_title(f'Original Audio Waveform - {f}')
  axes[0].grid(True, alpha=0.3)

  # residual energies for different orders
  colors = plt.cm.viridis(np.linspace(0.8, 1, len(lp_orders)))
  for idx, order in enumerate(lp_orders):
      axes[1].plot(frame_times, 10*np.log10(residual_energies[order] + 1e-10),
                  label=f'Order N={order}', color=colors[idx], linewidth=1.2)

  axes[1].set_xlabel('Time (s)')
  axes[1].set_ylabel('Residual Energy (dB)')
  axes[1].set_title(f'Residual Energy vs Frame for Different LP Orders {f}')
  axes[1].legend(loc='upper right')
  axes[1].grid(True, alpha=0.3)

  # Plot frame energy and residual energy (for order=12)
  axes[2].plot(frame_times, 10*np.log10(frame_energies + 1e-10),
              'b-', label='Frame Energy', linewidth=1.2, alpha=0.7)
  axes[2].plot(frame_times, 10*np.log10(residual_energies[12] + 1e-10),
              'r-', label='Residual Energy (N=12)', linewidth=1.2, alpha=0.7)
  axes[2].set_xlabel('Time (s)')
  axes[2].set_ylabel('Energy (dB)')
  axes[2].set_title(f'Comparison: Frame Energy vs Residual Energy (LP Order=12) , {f}')
  axes[2].legend(loc='upper right')
  axes[2].grid(True, alpha=0.3)

  plt.tight_layout()
  plt.savefig('residual_energy_plot.png', dpi=150, bbox_inches='tight')
  plt.show()

plot(lp_orders , residual_energies, frame_energies , "")

def plot_g(audio , frame_energies , f):

  # Gain: G = 10*log10(Frame Energy / Residual Energy) . Higher prediction gain indicates more predictable signal (voiced speech)

  fig, axes = plt.subplots(2, 1, figsize=(14, 8))
  time_audio = np.arange(len(audio)) / sample_rate
  frame_times = np.arange(num_frames) * hop_duration
  colors = plt.cm.viridis(np.linspace(0.8, 1, len(lp_orders)))
  # Plot original waveform
  axes[0].plot(time_audio, audio, 'b-', linewidth=0.5)
  axes[0].set_xlabel('Time (s)')
  axes[0].set_ylabel('Amplitude')
  axes[0].set_title(f'Original Audio Waveform {f}')
  axes[0].grid(True, alpha=0.3)

  for idx, order in enumerate(lp_orders):
      prediction_gain = 10 * np.log10((frame_energies + 1e-10) / (residual_energies[order] + 1e-10))
      axes[1].plot(frame_times, prediction_gain,
                  label=f'Order N={order}', color=colors[idx], linewidth=1.2)

  axes[1].set_xlabel('Time (s)')
  axes[1].set_ylabel('Prediction Gain (dB)')
  axes[1].set_title(f'Prediction Gain vs Frame for Different LP Orders {f}')
  axes[1].legend(loc='upper right')
  axes[1].grid(True, alpha=0.3)

  plt.tight_layout()
  plt.savefig('prediction_gain_plot.png', dpi=150, bbox_inches='tight')
  plt.show()

  print("\n=== Prediction Gain Statistics (dB) ===")
  for order in lp_orders:
      prediction_gain = 10 * np.log10((frame_energies + 1e-10) / (residual_energies[order] + 1e-10))
      print(f"Order N={order}: Mean={np.mean(prediction_gain):.2f}, Max={np.max(prediction_gain):.2f}, Min={np.min(prediction_gain):.2f}")

plot_g(audio , frame_energies , "")

import os
for f in os.listdir("/content/dataFiles"):
  sample_rate , audio = load_audio(f"dataFiles/{f}")
  num_frames , window_length , hop_length , window = get_window(sample_rate , audio)
  lp_orders , residual_energies, frame_energies = compute_audio_residual(num_frames , window_length , hop_length , window)
  plot(lp_orders , residual_energies, frame_energies , f)
  plot_g(audio , frame_energies , f)

"""# 5.b"""

from numpy.fft import fft

def lpc_spectrum_from_coeffs(lp_coeffs, nfft):
    """
    Convert LPC (AR) coefficients to spectral envelope |H(e^jw)|
    H(z) = 1 / (1 + sum a_k z^-k)
    """
    a = np.concatenate([[1], lp_coeffs])

    # Frequency response of AR filter
    A = fft(a, nfft)
    H = 1.0 / (np.abs(A) + 1e-10)   # magnitude envelope

    return H

def stft_analysis(audio, window, hop_length, nfft):
    frames = []
    phases = []

    for i in range(num_frames):
        start = i * hop_length
        frame = audio[start:start+len(window)] * window

        spectrum = fft(frame, nfft)

        frames.append(np.abs(spectrum))
        phases.append(np.angle(spectrum))

    return np.array(frames), np.array(phases)

def apply_lpc_envelope(audio, order, nfft):
    reconstructed_spec = []
    _, phases = stft_analysis(audio, window, hop_length, nfft)

    for i in range(num_frames):
        start = i * hop_length
        frame = audio[start:start+window_length] * window

        lp_coeffs, _ = compute_lp_coefficients(frame, order)

        # LPC envelope
        H = lpc_spectrum_from_coeffs(lp_coeffs, nfft)

        # Use ORIGINAL PHASE
        complex_spec = H * np.exp(1j * phases[i])
        reconstructed_spec.append(complex_spec)

    return np.array(reconstructed_spec)

def istft_synthesis(spec_frames, window, hop_length):
    nfft = spec_frames.shape[1]
    output_len = (num_frames-1)*hop_length + window_length
    output = np.zeros(output_len)

    for i, spectrum in enumerate(spec_frames):
        frame = np.real(np.fft.ifft(spectrum))[:window_length]
        start = i * hop_length
        output[start:start+window_length] += frame * window

    # Normalize overlap
    output /= np.max(np.abs(output) + 1e-10)
    return output

def synthesize_from_noise(order):
    synthesized = np.zeros((num_frames-1)*hop_length + window_length)

    for i in range(num_frames):
        # White noise excitation
        excitation = np.random.randn(window_length)

        start = i * hop_length
        frame = audio[start:start+window_length] * window

        lp_coeffs, gain = compute_lp_coefficients(frame, order)

        # LPC synthesis filter: 1 / A(z)
        a = np.concatenate([[1], lp_coeffs])

        synth_frame = lfilter([1], a, excitation)

        synthesized[start:start+window_length] += synth_frame * window

    synthesized /= np.max(np.abs(synthesized)+1e-10)
    return synthesized

from IPython.display import Audio

nfft = 1024
order = 12

lpc_modified_spec = apply_lpc_envelope(audio, order, nfft)
reconstructed_audio = istft_synthesis(lpc_modified_spec, window, hop_length)

wav.write("reconstructed_from_LPC_phase.wav",
          sample_rate,
          reconstructed_audio.astype(np.float32))

Audio("reconstructed_from_LPC_phase.wav")

noise_speech = synthesize_from_noise(order=12)

wav.write("white_noise_LPC_synthesis.wav",
          sample_rate,
          noise_speech.astype(np.float32))
Audio("white_noise_LPC_synthesis.wav")

"""# 6"""

def compute_psd(frame, nfft=1024):
    X = np.fft.rfft(frame, nfft)
    Sxx = (np.abs(X)**2) / len(frame)
    return Sxx

def stlp_autocorrelation(Sxx, q, order):
    """
    r_q[k] = IDTFT{ Sxx^(1/q) }
    """
    S_mod = Sxx ** (1.0/q)

    # Recreate symmetric spectrum for IFFT
    full_spec = np.concatenate([S_mod, S_mod[-2:0:-1]])
    r = np.real(np.fft.ifft(full_spec))

    return r[:order+1]

def solve_lp_from_r(r, order):
    R = toeplitz(r[:-1])
    a = np.linalg.solve(R, -r[1:])
    return a

def ar_psd(a, nfft=1024):
    A = np.fft.rfft(np.concatenate([[1], a]), nfft)
    H = 1.0 / (np.abs(A)**2 + 1e-12)
    return H

def stlp_estimate(frame, order, q, nfft=1024):

    Sxx = compute_psd(frame, nfft)

    r_q = stlp_autocorrelation(Sxx, q, order)

    a = solve_lp_from_r(r_q, order)

    S_hat_root = ar_psd(a, nfft)

    # Undo compression
    S_hat = S_hat_root ** q

    return Sxx, S_hat

def is_voiced(frame, zcr_thresh=0.08, energy_thresh=0.001):

    zcr = np.mean(np.abs(np.diff(np.sign(frame)))) / 2
    energy = np.mean(frame**2)

    return (zcr < zcr_thresh) and (energy > energy_thresh)

orders = 12
qs = [1,2,3,4,5]

mse_voiced = {q:[] for q in qs}
mse_unvoiced = {q:[] for q in qs}

nfft = 1024

for i in range(num_frames):

    start = i*hop_length
    frame = audio[start:start+window_length]*window

    if len(frame) < window_length:
        continue

    voiced_flag = is_voiced(frame)

    for q in qs:

        Sxx, S_hat = stlp_estimate(frame, orders, q, nfft)

        # Log spectral error (perceptually meaningful)
        err = np.mean((10*np.log10(Sxx+1e-10) -
                       10*np.log10(S_hat+1e-10))**2)

        if voiced_flag:
            mse_voiced[q].append(err)
        else:
            mse_unvoiced[q].append(err)

mean_voiced   = [np.mean(mse_voiced[q]) for q in qs]
mean_unvoiced = [np.mean(mse_unvoiced[q]) for q in qs]

plt.figure(figsize=(7,5))
plt.plot(qs, mean_voiced, marker='o', label="Voiced")
plt.plot(qs, mean_unvoiced, marker='s', label="Unvoiced")
plt.xlabel("q")
plt.ylabel("Mean Log-Spectral MSE")
plt.title("STLP Approximation Error vs q")
plt.legend()
plt.grid(True)
plt.show()

def find_example_frame(target_voiced=True):
    for i in range(num_frames):
        start=i*hop_length
        frame=audio[start:start+window_length]*window
        if is_voiced(frame)==target_voiced:
            return frame

def plot_stlp_comparison(frame):

    plt.figure(figsize=(8,5))

    Sxx = compute_psd(frame)

    plt.plot(10*np.log10(Sxx+1e-10), linewidth=3, label="True PSD")

    for q in [1,2,3,4]:
        _, S_hat = stlp_estimate(frame, 12, q)
        plt.plot(10*np.log10(S_hat+1e-10), linestyle='--', label=f"q={q}")

    plt.title("STLP Spectral Approximation")
    plt.xlabel("Frequency Bin")
    plt.ylabel("Power (dB)")
    plt.legend()
    plt.grid(True)
    plt.show()

plot_stlp_comparison(find_example_frame(True))   # voiced
plot_stlp_comparison(find_example_frame(False))  # unvoiced



import numpy as np
import matplotlib.pyplot as plt
import wave
import struct

############################################################
# AUDIO LOADING (no librosa — implemented from scratch)
############################################################

def load_wav(path):
    wav = wave.open(path, 'r')
    n_channels = wav.getnchannels()
    fs = wav.getframerate()
    n_frames = wav.getnframes()

    frames = wav.readframes(n_frames)
    samples = struct.unpack('<' + 'h'*n_frames*n_channels, frames)
    signal = np.array(samples, dtype=np.float64)

    if n_channels > 1:
        signal = signal.reshape(-1, n_channels).mean(axis=1)

    signal /= np.max(np.abs(signal))  # normalize
    return signal, fs

############################################################
# FRAME EXTRACTION
############################################################

def extract_frame(signal, fs, start_time, frame_length_ms=30):
    N = int(frame_length_ms * 1e-3 * fs)
    start = int(start_time * fs)
    frame = signal[start:start+N]

    # Hamming window (manual)
    n = np.arange(len(frame))
    window = 0.54 - 0.46*np.cos(2*np.pi*n/(len(frame)-1))
    return frame * window

############################################################
# AUTOCORRELATION (manual implementation)
############################################################

def autocorrelation(x, order):
    N = len(x)
    r = np.zeros(order+1)

    for k in range(order+1):
        for n in range(N-k):
            r[k] += x[n]*x[n+k]
    return r

############################################################
# LEVINSON-DURBIN (from scratch)
############################################################

def levinson_durbin(r, order):
    a = np.zeros(order+1)
    e = r[0]

    a[0] = 1.0

    for i in range(1, order+1):
        acc = 0.0
        for j in range(1, i):
            acc += a[j]*r[i-j]

        k = -(r[i] + acc)/e

        a_prev = a.copy()
        a[i] = k

        for j in range(1, i):
            a[j] = a_prev[j] + k*a_prev[i-j]

        e *= (1 - k*k)

    return a, e

############################################################
# DTFT (explicit computation)
############################################################

def compute_dtft_psd(x, nfft=1024):
    w = np.linspace(0, np.pi, nfft)
    S = np.zeros(nfft)

    for i, wi in enumerate(w):
        acc_real = 0.0
        acc_imag = 0.0
        for n in range(len(x)):
            acc_real += x[n]*np.cos(-wi*n)
            acc_imag += x[n]*np.sin(-wi*n)
        S[i] = acc_real**2 + acc_imag**2

    return w, S

############################################################
# LP SPECTRUM FROM COEFFICIENTS
############################################################

def lp_spectrum(a, e, nfft=1024):
    w = np.linspace(0, np.pi, nfft)
    A = np.zeros(nfft)

    for i, wi in enumerate(w):
        real = 0.0
        imag = 0.0
        for k in range(len(a)):
            real += a[k]*np.cos(-wi*k)
            imag += a[k]*np.sin(-wi*k)
        A[i] = e / (real**2 + imag**2)

    return w, A

############################################################
# SPECTRAL TRANSFORM AUTOCORRELATION
############################################################

def plot_stlp_both_cases(voiced_frame, unvoiced_frame, fs, order, q_values, fname):
    fig = plt.figure(figsize=(12, 5))
    subfigs = fig.subfigures(1, 2, wspace=0.07)

    cases = [
        ("Voiced", voiced_frame),
        ("Unvoiced", unvoiced_frame)
    ]

    for subfig, (label, frame) in zip(subfigs, cases):
        w_true, S_true = compute_dtft_psd(frame)

        ax = subfig.subplots(1, 1)

        ax.plot(w_true, np.log(S_true + 1e-12), label="True PSD")

        for q in q_values:
            a, e = stlp_analysis(frame, order, q)
            w_lp, S_lp = lp_spectrum(a, e)
            ax.plot(w_lp, np.log(S_lp + 1e-12), label=f"q={q}")

        subfig.suptitle(label, fontsize=13, fontweight='bold')
        ax.set_xlabel("Frequency (rad)")
        ax.set_ylabel("Log Spectrum")
        ax.legend()

    fig.suptitle(f"STLP Comparison — {fname} (N = {order})",
                 fontsize=16, fontweight='bold')

    plt.tight_layout()
    plt.show()



def plot_stlp_per_q(voiced_frame, unvoiced_frame, fs, order, q_values, fname):
    fig = plt.figure(figsize=(14, 4 * len(q_values)))
    subfigs = fig.subfigures(1, 2, wspace=0.08)

    cases = [
        ("Voiced", voiced_frame),
        ("Unvoiced", unvoiced_frame)
    ]

    for subfig, (label, frame) in zip(subfigs, cases):
        w_true, S_true = compute_dtft_psd(frame)

        axes = subfig.subplots(len(q_values), 1)
        if len(q_values) == 1:
            axes = [axes]

        for idx, q in enumerate(q_values):
            a, e = stlp_analysis(frame, order, q)
            w_lp, S_lp = lp_spectrum(a, e)

            axes[idx].plot(w_true, np.log(S_true + 1e-12), label="True PSD")
            axes[idx].plot(w_lp, np.log(S_lp + 1e-12), label=f"STLP q={q}")

            axes[idx].set_title(f"q = {q}")
            axes[idx].set_xlabel("Frequency (rad)")
            axes[idx].set_ylabel("Log Spectrum")
            axes[idx].legend()

        subfig.suptitle(label, fontsize=13, fontweight='bold')

    fig.suptitle(
        f"STLP Spectral Approximation",
        fontsize=12,
        fontweight='bold'
    )

    plt.tight_layout()
    plt.show()

def plot_stlp_comparison(voiced_frame, unvoiced_frame, fs, order, q_values, fname):
    fig = plt.figure(figsize=(12, 5))
    subfigs = fig.subfigures(1, 2, wspace=0.08)

    cases = [
        ("Voiced", voiced_frame),
        ("Unvoiced", unvoiced_frame)
    ]

    for subfig, (label, frame) in zip(subfigs, cases):
        w_true, S_true = compute_dtft_psd(frame)
        ax = subfig.subplots(1, 1)

        ax.plot(w_true, np.log(S_true + 1e-12), label="True PSD")

        for q in q_values:
            a, e = stlp_analysis(frame, order, q)
            w_lp, S_lp = lp_spectrum(a, e)
            ax.plot(w_lp, np.log(S_lp + 1e-12), label=f"q={q}")

        ax.set_title(label)
        ax.set_xlabel("Frequency (rad)")
        ax.set_ylabel("Log Spectrum")
        ax.legend()

    fig.suptitle(
        f"STLP Comparison Across q — {fname} (N = {order})",
        fontsize=16,
        fontweight='bold'
    )

    plt.tight_layout()
    plt.show()

############################################################
# COMPLETE STLP PIPELINE
############################################################
def spectral_transform_autocorr(frame, q, order, nfft=1024):
    """
    Compute STLP transformed autocorrelation.

    Steps:
    1. Compute DTFT PSD of frame
    2. Apply spectral compression (power q)
    3. Inverse DTFT to obtain autocorrelation
    """

    # ---- Step 1: DTFT PSD ----
    w, S = compute_dtft_psd(frame, nfft=nfft)

    # ---- Step 2: spectral compression ----
    S_q = S ** q

    # ---- Step 3: inverse DTFT to get autocorrelation ----
    r_tilde = np.zeros(order + 1)

    dw = np.pi / (nfft - 1)

    for k in range(order + 1):
        acc = 0.0
        for i in range(nfft):
            acc += S_q[i] * np.cos(w[i] * k)
        r_tilde[k] = acc * dw / np.pi

    # ---- numerical safety ----
    if r_tilde[0] <= 0:
        r_tilde[0] = 1e-6

    return r_tilde

def stlp_analysis(frame, order, q):
    r_tilde = spectral_transform_autocorr(frame, q, order)
    a, e = levinson_durbin(r_tilde, order)
    return a, e

############################################################
# PLOTTING UTILITIES
############################################################

def plot_time_signal(frame, title):
    plt.figure(figsize=(6,4))
    plt.plot(frame)
    plt.title(title)
    plt.xlabel("Samples")
    plt.ylabel("Amplitude")
    plt.show()

def plot_autocorr(r, title):
    plt.figure(figsize=(6,4))
    plt.stem(r)
    plt.title(title)
    plt.xlabel("Lag")
    plt.ylabel("Value")
    plt.show()

def compare_spectra(frame, order, q_values):
    w_true, S_true = compute_dtft_psd(frame)

    plt.figure(figsize=(6,4))
    plt.plot(w_true, np.log(S_true + 1e-12))

    for q in q_values:
        a, e = stlp_analysis(frame, order, q)
        w_lp, S_lp = lp_spectrum(a, e)
        plt.plot(w_lp, np.log(S_lp + 1e-12))

    plt.title("True PSD vs STLP Approximations")
    plt.xlabel("Frequency (rad)")
    plt.ylabel("Log Spectrum")
    plt.show()

############################################################
# MAIN EXPERIMENT
############################################################

def run_experiment(audio_path):
    fname = audio_path.split("/")[-1]

    signal, fs = load_wav(audio_path)

    # ---- Select frames (adjust times if needed) ----
    voiced_frame   = extract_frame(signal, fs, start_time=0.3)
    unvoiced_frame = extract_frame(signal, fs, start_time=1.0)

    LP_ORDER = 16
    q_values = [1, 2, 3]

    # ---- Time-domain inspection ----
    plot_time_signal(voiced_frame,   f"Voiced Frame — {fname}")
    plot_time_signal(unvoiced_frame, f"Unvoiced Frame — {fname}")

    # ---- STLP Spectral Analysis ----
    plot_stlp_per_q(voiced_frame, unvoiced_frame, fs, LP_ORDER, q_values, fname)
    plot_stlp_comparison(voiced_frame, unvoiced_frame, fs, LP_ORDER, q_values, fname)


for f in os.listdir("/content/dataFiles"):
  audio_path =f"/content/dataFiles/{f}"
  run_experiment(audio_path)

import numpy as np
import scipy.io.wavfile as wav
from scipy.signal.windows import hamming
from scipy.signal import lfilter
from scipy.linalg import toeplitz
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import os

# ─────────────────────────────────────────────────────────────
# CORE UTILITIES
# ─────────────────────────────────────────────────────────────

def load_audio(file_loc):
    sample_rate, audio = wav.read(file_loc)
    audio = audio.astype(np.float64)
    audio = audio / np.max(np.abs(audio))
    print(f"Sample Rate: {sample_rate} Hz | Length: {len(audio)/sample_rate:.3f}s")
    return sample_rate, audio

def get_stft_params(sample_rate, window_duration=0.025, hop_duration=0.010):
    window_length = int(window_duration * sample_rate)
    hop_length    = int(hop_duration   * sample_rate)
    window        = hamming(window_length)
    return window_length, hop_length, window

# ─────────────────────────────────────────────────────────────
# STFT (from scratch)
# ─────────────────────────────────────────────────────────────

def compute_stft(audio, window, hop_length):
    """Returns complex STFT: shape (num_frames, nfft//2+1)."""
    wl = len(window)
    nfft = wl
    num_frames = (len(audio) - wl) // hop_length + 1
    stft = np.zeros((num_frames, nfft // 2 + 1), dtype=complex)
    for i in range(num_frames):
        frame = audio[i*hop_length : i*hop_length + wl] * window
        stft[i] = np.fft.rfft(frame, n=nfft)
    return stft

# ─────────────────────────────────────────────────────────────
# PSD: S_xx(e^jw) — magnitude squared of STFT
# ─────────────────────────────────────────────────────────────

def compute_psd(stft):
    """Per-frame power spectral density |X(e^jw)|^2."""
    return np.abs(stft) ** 2

# ─────────────────────────────────────────────────────────────
# STLP: Spectral Transform Linear Prediction
#
#  Step 1: Compute S_xx(e^jw)^(1/q)  — power-compress the PSD
#  Step 2: Inverse DFT → autocorrelation-like sequence r_q[n]
#  Step 3: Solve Yule-Walker (Toeplitz) for LP coefficients
#  Step 4: AR model gives Ŝ_xx(e^jw)  (LP envelope of compressed PSD)
#  Step 5: Raise to power q → Ŝ_xx(e^jw)^q ≈ S_xx(e^jw)
# ─────────────────────────────────────────────────────────────

def compute_lp_coefficients_from_autocorr(r, order):
    """Solve Yule-Walker equations via Toeplitz system."""
    r_norm = r / (r[0] + 1e-10)
    R = toeplitz(r_norm[:order])
    try:
        a = np.linalg.solve(R, -r_norm[1:order+1])
    except np.linalg.LinAlgError:
        a = np.zeros(order)
    return a

def ar_spectrum(lp_coeffs, gain, nfft):
    """
    AR (all-pole) model spectrum magnitude squared:
    Ŝ(e^jw) = gain^2 / |A(e^jw)|^2
    A(e^jw) = 1 + a1*e^{-jw} + ... + ap*e^{-jpw}
    """
    a_full = np.concatenate([[1], lp_coeffs])
    # Zero-pad to nfft for frequency resolution
    A_freq = np.fft.rfft(a_full, n=nfft)
    psd_ar = (gain ** 2) / (np.abs(A_freq) ** 2 + 1e-30)
    return psd_ar

def stlp_frame(frame_psd, order, q, nfft):
    """
    STLP for a single frame.

    Parameters
    ----------
    frame_psd : np.ndarray  — S_xx(e^jw), shape (nfft//2+1,)
    order     : int         — LP order
    q         : int         — compression exponent
    nfft      : int

    Returns
    -------
    S_hat_q   : np.ndarray  — Ŝ_xx(e^jw)^q, the final AR PSD approximation
    S_hat_1q  : np.ndarray  — Ŝ_xx(e^jw), AR model of S^(1/q)
    """
    # Step 1: Power-compress the PSD → S_xx^(1/q)
    S_compressed = frame_psd ** (1.0 / q)           # shape: (nfft//2+1,)

    # Step 2: Reconstruct full two-sided spectrum (symmetric) and IDFT
    # Build real, symmetric full DFT from one-sided
    if nfft % 2 == 0:
        S_full = np.concatenate([S_compressed, S_compressed[-2:0:-1]])
    else:
        S_full = np.concatenate([S_compressed, S_compressed[-1:0:-1]])
    # IDFT → autocorrelation sequence r_q[n]
    r_q = np.real(np.fft.ifft(S_full))              # shape: (nfft,)

    # Step 3: Solve Yule-Walker with r_q[0:order+1]
    r_lp = r_q[:order+1]
    a    = compute_lp_coefficients_from_autocorr(r_lp, order)

    # Step 4: Gain^2 = r_q[0] + sum(a * r_q[1:p+1])
    gain_sq = np.real(r_lp[0] + np.dot(a, r_lp[1:order+1]))
    gain_sq = max(gain_sq, 1e-10)

    # Step 5a: AR model of compressed PSD → Ŝ(e^jw)  (approximates S^(1/q))
    S_hat_1q = ar_spectrum(a, np.sqrt(gain_sq), nfft)   # one-sided

    # Step 5b: Raise back to power q → approximates original PSD
    S_hat_q  = S_hat_1q ** q

    return S_hat_q, S_hat_1q

def run_stlp(audio, sample_rate, order=12, q_values=(1, 2, 3)):
    """
    Run STLP on all frames for each q value.

    Returns
    -------
    results : dict  keyed by q, each value is dict with:
              'S_hat_q'  : (num_frames, nfft//2+1) — approximation of PSD
              'S_hat_1q' : (num_frames, nfft//2+1) — AR model of S^(1/q)
    psd_orig : (num_frames, nfft//2+1) — original PSD S_xx
    freqs    : frequency axis (Hz)
    frames   : list of frame indices
    """
    window_length, hop_length, window = get_stft_params(sample_rate)
    nfft = window_length

    stft     = compute_stft(audio, window, hop_length)
    psd_orig = compute_psd(stft)                         # S_xx(e^jw)
    num_frames = psd_orig.shape[0]
    freqs    = np.fft.rfftfreq(nfft, d=1/sample_rate)

    results = {}
    for q in q_values:
        S_hat_q_all  = np.zeros_like(psd_orig)
        S_hat_1q_all = np.zeros_like(psd_orig)
        for i in range(num_frames):
            S_hat_q_all[i], S_hat_1q_all[i] = stlp_frame(psd_orig[i], order, q, nfft)
        results[q] = {'S_hat_q': S_hat_q_all, 'S_hat_1q': S_hat_1q_all}

    return results, psd_orig, freqs, num_frames, hop_length, nfft

# ─────────────────────────────────────────────────────────────
# VOICED / UNVOICED DETECTION (simple energy + ZCR heuristic)
# ─────────────────────────────────────────────────────────────

def detect_voiced_unvoiced(audio, sample_rate, num_frames, hop_length, window_length):
    """
    Returns array of booleans: True = voiced, for each frame.
    Uses short-time energy + zero crossing rate.
    """
    wl = window_length
    energies, zcrs = [], []
    for i in range(num_frames):
        s = i * hop_length
        frame = audio[s:s+wl]
        energies.append(np.sum(frame**2) / wl)
        zcrs.append(np.sum(np.abs(np.diff(np.sign(frame)))) / (2 * wl))
    energies = np.array(energies)
    zcrs     = np.array(zcrs)

    # Voiced: high energy AND low ZCR
    energy_thresh = np.percentile(energies, 40)
    zcr_thresh    = np.percentile(zcrs, 60)
    voiced = (energies > energy_thresh) & (zcrs < zcr_thresh)
    return voiced, energies, zcrs

# ─────────────────────────────────────────────────────────────
# LOG SPECTRAL DISTANCE per frame
# ─────────────────────────────────────────────────────────────

def log_spectral_distance(psd1, psd2):
    """Per-frame LSD (dB) between two PSD arrays."""
    return np.sqrt(np.mean(
        (10*np.log10(psd1+1e-10) - 10*np.log10(psd2+1e-10))**2,
        axis=1
    ))

# ─────────────────────────────────────────────────────────────
# PICK BEST VOICED & UNVOICED FRAME
# ─────────────────────────────────────────────────────────────

def pick_frames(voiced_mask, energies, num_frames):
    """Return index of best voiced and best unvoiced frame."""
    voiced_idx   = np.where(voiced_mask)[0]
    unvoiced_idx = np.where(~voiced_mask)[0]

    if len(voiced_idx) == 0:
        voiced_idx = [num_frames // 3]
    if len(unvoiced_idx) == 0:
        unvoiced_idx = [num_frames * 2 // 3]

    v_frame  = voiced_idx[np.argmax(energies[voiced_idx])]
    uv_frame = unvoiced_idx[np.argmax(energies[unvoiced_idx])]
    return int(v_frame), int(uv_frame)

# ─────────────────────────────────────────────────────────────
# PLOTS
# ─────────────────────────────────────────────────────────────

COLORS = {1: '#e74c3c', 2: '#2ecc71', 3: '#3498db'}
QNAMES = {1: 'q=1 (Standard LP)', 2: 'q=2', 3: 'q=3'}

def plot_single_frame_analysis(freqs, psd_orig, results, frame_idx,
                                frame_label, q_values, fname=""):
    """
    Deep single-frame analysis:
    Row 0: S_xx vs Ŝ_xx^q  for each q (PSD in dB)
    Row 1: S_xx^(1/q) vs Ŝ_xx (AR of compressed PSD)
    Row 2: Approximation error |S_xx - Ŝ_xx^q| in dB
    """
    S_orig = psd_orig[frame_idx]
    fig, axes = plt.subplots(3, 1, figsize=(12, 11))
    fig.suptitle(f'STLP Single Frame Analysis — {frame_label} Frame (idx={frame_idx})\n{fname}',
                 fontsize=12, fontweight='bold')

    # Row 0: Original PSD vs Ŝ^q for each q
    axes[0].plot(freqs/1000, 10*np.log10(S_orig+1e-10),
                 'k-', lw=2, label='$S_{xx}(e^{j\\omega})$ — Original PSD', zorder=5)
    for q in q_values:
        S_hat_q = results[q]['S_hat_q'][frame_idx]
        axes[0].plot(freqs/1000, 10*np.log10(S_hat_q+1e-10),
                     color=COLORS[q], lw=1.5, ls='--', label=f'$\\hat{{S}}^{q}$  {QNAMES[q]}')
    axes[0].set_xlabel('Frequency (kHz)')
    axes[0].set_ylabel('Power (dB)')
    axes[0].set_title('Original PSD vs STLP Approximation $\\hat{S}_{xx}(e^{j\\omega})^q$')
    axes[0].legend(fontsize=9); axes[0].grid(True, alpha=0.3)
    axes[0].set_xlim([0, freqs[-1]/1000])

    # Row 1: Compressed PSD and its AR envelope
    for q in q_values:
        S_compressed = S_orig ** (1.0 / q)
        S_hat_1q     = results[q]['S_hat_1q'][frame_idx]
        axes[1].plot(freqs/1000, 10*np.log10(S_compressed+1e-10),
                     color=COLORS[q], lw=0.8, alpha=0.4,
                     label=f'$S_{{xx}}^{{1/{q}}}$ compressed')
        axes[1].plot(freqs/1000, 10*np.log10(S_hat_1q+1e-10),
                     color=COLORS[q], lw=1.8, ls='--',
                     label=f'$\\hat{{S}}_{{xx}}$ AR envelope (q={q})')
    axes[1].set_xlabel('Frequency (kHz)')
    axes[1].set_ylabel('Power (dB)')
    axes[1].set_title('Compressed PSD $S^{1/q}$ and its AR Spectral Envelope $\\hat{S}_{xx}$')
    axes[1].legend(fontsize=8, ncol=2); axes[1].grid(True, alpha=0.3)
    axes[1].set_xlim([0, freqs[-1]/1000])

    # Row 2: Absolute approximation error in dB
    for q in q_values:
        S_hat_q = results[q]['S_hat_q'][frame_idx]
        error_db = np.abs(10*np.log10(S_orig+1e-10) - 10*np.log10(S_hat_q+1e-10))
        axes[2].plot(freqs/1000, error_db,
                     color=COLORS[q], lw=1.5, label=f'|Error| dB  (q={q})  mean={np.mean(error_db):.2f}dB')
    axes[2].set_xlabel('Frequency (kHz)')
    axes[2].set_ylabel('|Error| (dB)')
    axes[2].set_title('Absolute Approximation Error $|S_{xx} - \\hat{S}_{xx}^q|$ (dB)')
    axes[2].legend(fontsize=9); axes[2].grid(True, alpha=0.3)
    axes[2].set_xlim([0, freqs[-1]/1000])

    plt.tight_layout()
    safe = fname.replace("/","_").replace(".","_")
    plt.savefig(f'stlp_frame_{frame_label}_{safe}.png', dpi=150, bbox_inches='tight')
    plt.show()


def plot_voiced_vs_unvoiced(freqs, psd_orig, results, v_idx, uv_idx, q_values, fname=""):
    """Side-by-side voiced vs unvoiced comparison for all q."""
    fig, axes = plt.subplots(len(q_values), 2, figsize=(16, 4*len(q_values)))
    fig.suptitle(f'STLP: Voiced vs Unvoiced Frame — {fname}', fontsize=12, fontweight='bold')

    frame_pairs = [(v_idx, 'Voiced'), (uv_idx, 'Unvoiced')]
    for row, q in enumerate(q_values):
        for col, (fidx, flabel) in enumerate(frame_pairs):
            ax = axes[row, col]
            S_orig  = psd_orig[fidx]
            S_hat_q = results[q]['S_hat_q'][fidx]

            ax.plot(freqs/1000, 10*np.log10(S_orig+1e-10),
                    'k-', lw=2, alpha=0.85, label='$S_{xx}$ Original')
            ax.plot(freqs/1000, 10*np.log10(S_hat_q+1e-10),
                    color=COLORS[q], lw=1.8, ls='--',
                    label=f'$\\hat{{S}}^{q}$ STLP (q={q})')

            lsd = np.sqrt(np.mean(
                (10*np.log10(S_orig+1e-10) - 10*np.log10(S_hat_q+1e-10))**2
            ))
            ax.set_title(f'{flabel} | q={q} | LSD={lsd:.2f} dB')
            ax.set_xlabel('Frequency (kHz)'); ax.set_ylabel('Power (dB)')
            ax.legend(fontsize=9); ax.grid(True, alpha=0.3)
            ax.set_xlim([0, freqs[-1]/1000])

    plt.tight_layout()
    safe = fname.replace("/","_").replace(".","_")
    plt.savefig(f'stlp_voiced_unvoiced_{safe}.png', dpi=150, bbox_inches='tight')
    plt.show()


def plot_lsd_over_time(psd_orig, results, voiced_mask, num_frames, hop_length,
                       sample_rate, q_values, fname=""):
    """LSD over time with voiced/unvoiced regions highlighted."""
    frame_times = np.arange(num_frames) * (hop_length / sample_rate)

    fig, axes = plt.subplots(2, 1, figsize=(14, 9))
    fig.suptitle(f'STLP — Log Spectral Distance Over Time — {fname}',
                 fontsize=12, fontweight='bold')

    # LSD per frame per q
    for q in q_values:
        lsd = log_spectral_distance(psd_orig, results[q]['S_hat_q'])
        axes[0].plot(frame_times, lsd, color=COLORS[q], lw=1.4,
                     label=f'q={q}  mean={np.mean(lsd):.2f} dB')

    # Shade voiced regions
    in_voiced = False
    for i, v in enumerate(voiced_mask):
        if v and not in_voiced:
            start = frame_times[i]; in_voiced = True
        elif not v and in_voiced:
            axes[0].axvspan(start, frame_times[i-1], alpha=0.12, color='gold', label='_')
            in_voiced = False
    if in_voiced:
        axes[0].axvspan(start, frame_times[-1], alpha=0.12, color='gold')

    # Dummy patch for legend
    from matplotlib.patches import Patch
    axes[0].legend(handles=[
        *[plt.Line2D([0],[0], color=COLORS[q], lw=2, label=f'q={q}') for q in q_values],
        Patch(color='gold', alpha=0.3, label='Voiced region')
    ], fontsize=9)
    axes[0].set_xlabel('Time (s)'); axes[0].set_ylabel('LSD (dB)')
    axes[0].set_title('Log Spectral Distance $S_{xx}$ vs $\\hat{S}_{xx}^q$ per Frame')
    axes[0].grid(True, alpha=0.3)

    # LSD: voiced-only vs unvoiced-only box plot style comparison
    lsd_data = {q: log_spectral_distance(psd_orig, results[q]['S_hat_q']) for q in q_values}
    voiced_lsd   = {q: lsd_data[q][voiced_mask]  for q in q_values}
    unvoiced_lsd = {q: lsd_data[q][~voiced_mask] for q in q_values}

    x = np.arange(len(q_values))
    width = 0.35
    v_means  = [np.mean(voiced_lsd[q])   for q in q_values]
    uv_means = [np.mean(unvoiced_lsd[q]) for q in q_values]
    v_stds   = [np.std(voiced_lsd[q])    for q in q_values]
    uv_stds  = [np.std(unvoiced_lsd[q])  for q in q_values]

    bars1 = axes[1].bar(x - width/2, v_means,  width, yerr=v_stds,  capsize=4,
                        color='#f1c40f', alpha=0.85, label='Voiced frames')
    bars2 = axes[1].bar(x + width/2, uv_means, width, yerr=uv_stds, capsize=4,
                        color='#95a5a6', alpha=0.85, label='Unvoiced frames')
    axes[1].set_xticks(x)
    axes[1].set_xticklabels([f'q={q}' for q in q_values])
    axes[1].set_ylabel('Mean LSD (dB)'); axes[1].set_xlabel('q value')
    axes[1].set_title('Mean LSD: Voiced vs Unvoiced Frames per q')
    axes[1].legend(fontsize=9); axes[1].grid(True, alpha=0.3, axis='y')

    # Annotate bars
    for bar in bars1:
        axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.1,
                     f'{bar.get_height():.2f}', ha='center', fontsize=8)
    for bar in bars2:
        axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.1,
                     f'{bar.get_height():.2f}', ha='center', fontsize=8)

    plt.tight_layout()
    safe = fname.replace("/","_").replace(".","_")
    plt.savefig(f'stlp_lsd_time_{safe}.png', dpi=150, bbox_inches='tight')
    plt.show()


def plot_spectrograms(psd_orig, results, num_frames, hop_length, sample_rate,
                      freqs, q_values, fname=""):
    """Spectrogram of original PSD and STLP approximations side by side."""
    frame_times = np.arange(num_frames) * (hop_length / sample_rate)
    n_plots = 1 + len(q_values)

    fig, axes = plt.subplots(1, n_plots, figsize=(5*n_plots, 6))
    fig.suptitle(f'STLP Spectrograms — {fname}', fontsize=12, fontweight='bold')

    vmin, vmax = -80, 0
    kw = dict(aspect='auto', origin='lower',
              extent=[0, frame_times[-1], 0, freqs[-1]/1000],
              vmin=vmin, vmax=vmax, cmap='magma')

    im = axes[0].imshow(10*np.log10(psd_orig.T + 1e-10), **kw)
    axes[0].set_title('$S_{xx}(e^{j\\omega})$ Original PSD')
    axes[0].set_xlabel('Time (s)'); axes[0].set_ylabel('Frequency (kHz)')

    for idx, q in enumerate(q_values):
        S_hat_q = results[q]['S_hat_q']
        im = axes[idx+1].imshow(10*np.log10(S_hat_q.T + 1e-10), **kw)
        axes[idx+1].set_title(f'$\\hat{{S}}_{{xx}}(e^{{j\\omega}})^{{{q}}}$ STLP q={q}')
        axes[idx+1].set_xlabel('Time (s)')
        axes[idx+1].set_ylabel('')

    plt.colorbar(im, ax=axes[-1], label='Power (dB)')
    plt.tight_layout()
    safe = fname.replace("/","_").replace(".","_")
    plt.savefig(f'stlp_spectrograms_{safe}.png', dpi=150, bbox_inches='tight')
    plt.show()


def print_statistics(psd_orig, results, voiced_mask, q_values):
    """Print LSD statistics per q for voiced and unvoiced."""
    print("\n" + "="*60)
    print("STLP Approximation Statistics")
    print("="*60)
    for q in q_values:
        lsd = log_spectral_distance(psd_orig, results[q]['S_hat_q'])
        print(f"\n  q={q}:")
        print(f"    Overall  — Mean: {np.mean(lsd):.2f} dB | Std: {np.std(lsd):.2f} dB | Max: {np.max(lsd):.2f} dB")
        if voiced_mask.sum() > 0:
            lv = lsd[voiced_mask]
            print(f"    Voiced   — Mean: {np.mean(lv):.2f} dB | Std: {np.std(lv):.2f} dB")
        if (~voiced_mask).sum() > 0:
            luv = lsd[~voiced_mask]
            print(f"    Unvoiced — Mean: {np.mean(luv):.2f} dB | Std: {np.std(luv):.2f} dB")

# ─────────────────────────────────────────────────────────────
# MAIN PIPELINE
# ─────────────────────────────────────────────────────────────

def run_stlp_analysis(file_path, order=12, q_values=(1, 2, 3)):
    fname = os.path.basename(file_path)
    print(f"\n{'='*60}\nProcessing: {fname}")

    sample_rate, audio = load_audio(file_path)
    window_length, hop_length, window = get_stft_params(sample_rate)

    # Run STLP
    results, psd_orig, freqs, num_frames, hop_length, nfft = \
        run_stlp(audio, sample_rate, order, q_values)

    # Voiced / Unvoiced detection
    voiced_mask, energies, zcrs = detect_voiced_unvoiced(
        audio, sample_rate, num_frames, hop_length, window_length)
    v_idx, uv_idx = pick_frames(voiced_mask, energies, num_frames)

    print(f"  Voiced frames: {voiced_mask.sum()} / {num_frames}")
    print(f"  Best voiced frame: {v_idx} | Best unvoiced frame: {uv_idx}")

    # ── Deep single-frame plots (voiced + unvoiced)
    plot_single_frame_analysis(freqs, psd_orig, results, v_idx,
                                'Voiced', q_values, fname)
    plot_single_frame_analysis(freqs, psd_orig, results, uv_idx,
                                'Unvoiced', q_values, fname)

    # ── Voiced vs Unvoiced side-by-side for all q
    plot_voiced_vs_unvoiced(freqs, psd_orig, results, v_idx, uv_idx, q_values, fname)

    # ── LSD over time + bar chart
    plot_lsd_over_time(psd_orig, results, voiced_mask, num_frames,
                       hop_length, sample_rate, q_values, fname)

    # ── Spectrogram comparison
    plot_spectrograms(psd_orig, results, num_frames, hop_length,
                      sample_rate, freqs, q_values, fname)

    # ── Statistics
    print_statistics(psd_orig, results, voiced_mask, q_values)


# Run on all files
for f in os.listdir("dataFiles"):
    run_stlp_analysis(f"dataFiles/{f}", order=12, q_values=[1, 2, 3])

