# -*- coding: utf-8 -*-
"""mixup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICPjIzPAIXxafLI13o9_Ploj26tz26un
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np
from torch.utils.data import DataLoader
from torch.distributions.beta import Beta
import random

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Normalize to [-1, 1]
normalize = transforms.Normalize((0.5, 0.5, 0.5),
                                 (0.5, 0.5, 0.5))

# Raw transform
transform_raw = transforms.Compose([
    transforms.ToTensor(),
    normalize
])

# Individual augmentations
transform_hflip = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    normalize
])

transform_crop = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.ToTensor(),
    normalize
])

transform_color = transforms.Compose([
    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2,
        hue=0.1
    ),
    transforms.ToTensor(),
    normalize
])

def get_loaders(transform_train, batch_size=512):

    trainset = torchvision.datasets.CIFAR10(
        root='./data',
        train=True,
        download=True,
        transform=transform_train
    )

    testset = torchvision.datasets.CIFAR10(
        root='./data',
        train=False,
        download=True,
        transform=transform_raw
    )

    trainloader = DataLoader(trainset, batch_size=batch_size,
                             shuffle=True, num_workers=2)

    testloader = DataLoader(testset, batch_size=batch_size,
                            shuffle=False, num_workers=2)

    return trainloader, testloader

class SimpleCNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 8 * 8, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Linear(128, 10)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

def mixup_data(x, y, alpha=1.0):
    if alpha > 0:
        lam = Beta(alpha, alpha).sample().item()
    else:
        lam = 1.0

    batch_size = x.size(0)
    index = torch.randperm(batch_size).to(device)

    mixed_x = lam * x + (1 - lam) * x[index]
    y_a, y_b = y, y[index]

    return mixed_x, y_a, y_b, lam


def mixup_criterion(criterion, pred, y_a, y_b, lam):
    return lam * criterion(pred, y_a) + (1 - lam) * criterion(pred, y_b)

def evaluate(model, loader, criterion):
    model.eval()
    total_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():
        for x, y in loader:
            x, y = x.to(device), y.to(device)

            outputs = model(x)
            loss = criterion(outputs, y)

            total_loss += loss.item()
            _, pred = outputs.max(1)
            total += y.size(0)
            correct += pred.eq(y).sum().item()

    acc = 100. * correct / total
    return total_loss / len(loader), acc

import matplotlib.pyplot as plt

def train_model(mode="raw", alpha=1.0, epochs=20):
    if mode == "raw":
        transform_train = transform_raw

    elif mode == "RandomHorizontalFlip":
        transform_train = transform_hflip

    elif mode == "RandomCrop":
        transform_train = transform_crop

    elif mode == "ColorJitter":
        transform_train = transform_color

    elif mode == "mixup":
        transform_train = transform_raw  # mixup works on raw tensors

    else:
        raise ValueError(f"Unknown mode: {mode}")

    trainloader, testloader = get_loaders(transform_train)


    model = SimpleCNN().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.0005)

    train_losses, val_losses, val_accs = [], [], []

    for epoch in range(epochs):
        model.train()
        running_loss = 0

        for x, y in trainloader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()

            if mode == "mixup":
                x, y_a, y_b, lam = mixup_data(x, y, alpha)
                outputs = model(x)
                loss = mixup_criterion(criterion, outputs, y_a, y_b, lam)
            else:
                outputs = model(x)
                loss = criterion(outputs, y)

            loss.backward()
            optimizer.step()
            running_loss += loss.item()

        train_loss = running_loss / len(trainloader)
        val_loss, val_acc = evaluate(model, testloader, criterion)

        train_losses.append(train_loss)
        val_losses.append(val_loss)
        val_accs.append(val_acc)

        print(f"{mode.upper()} Epoch {epoch+1}/{epochs} "
              f"Train Loss: {train_loss:.4f} "
              f"Val Acc: {val_acc:.2f}%")

    # 🔥 SINGLE COMBINED PLOT
    fig, ax1 = plt.subplots()

    ax1.plot(train_losses, label=f"Train Loss")
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("Train Loss")

    ax2 = ax1.twinx()
    ax2.plot(val_accs, label="Val Accuracy")
    ax2.set_ylabel("Validation Accuracy (%)")

    # combined legend
    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, labels1 + labels2, loc="best")

    if mode == "mixup":
        title = f"Training Curve ({mode}) alpha={alpha}"
        filename = f"{mode}_alpha{alpha}.png"
    else:
        title = f"Training Curve ({mode})"
        filename = f"{mode}.png"

    plt.title(title)
    plt.savefig(filename, bbox_inches="tight")
    plt.show()

    return model, train_losses, val_losses, val_accs[-1]

results = {}

print("\n=== RAW TRAINING ===")
results["raw"] = train_model("raw")

print("\n=== TRADITIONAL AUG ===")
results["RandomHorizontalFlip"] = train_model("RandomHorizontalFlip")


print("\n=== TRADITIONAL AUG ===")
results["RandomCrop"] = train_model("RandomCrop")


print("\n=== TRADITIONAL AUG ===")
results["ColorJitter"] = train_model("ColorJitter")

print("\n=== MIXUP (alpha=0.4) ===")
results["mixup"] = train_model("mixup", alpha=0.4)

train_model("mixup", alpha=0.1 , epochs=20)
train_model("mixup", alpha=0.2 , epochs=20)
train_model("mixup", alpha=0.8 , epochs=20)

train_model("mixup", alpha=0.2 , epochs=30)

def visualize_mixup(alpha=0.4):
    loader, _ = get_loaders(transform_raw, batch_size=8)
    x, y = next(iter(loader))
    x, y = x.to(device), y.to(device)

    mixed_x, _, _, lam = mixup_data(x, y, alpha)
    mixed_x = mixed_x.cpu()

    grid = torchvision.utils.make_grid(mixed_x[:8], nrow=4, normalize=True)
    plt.figure(figsize=(6,4))
    plt.imshow(np.transpose(grid.numpy(), (1,2,0)))
    plt.title(f"Mixup Samples (alpha={alpha}, lambda={lam:.2f})")
    plt.axis("off")
    plt.show()


visualize_mixup(0.2)
visualize_mixup(0.4)
visualize_mixup(1.0)

def visualize_mixup_subplot(alphas=[0.2, 0.4, 1.0]):
    loader, _ = get_loaders(transform_raw, batch_size=8)
    x, y = next(iter(loader))
    x, y = x.to(device), y.to(device)

    fig, axes = plt.subplots(1, len(alphas), figsize=(15, 4))

    if len(alphas) == 1:
        axes = [axes]

    for ax, alpha in zip(axes, alphas):
        mixed_x, _, _, lam = mixup_data(x, y, alpha)
        mixed_x = mixed_x.cpu()

        grid = torchvision.utils.make_grid(
            mixed_x[:8], nrow=4, normalize=True
        )

        ax.imshow(np.transpose(grid.numpy(), (1, 2, 0)))
        ax.set_title(f"alpha={alpha}, λ={lam:.2f}")
        ax.axis("off")

    plt.tight_layout()
    plt.show()

visualize_mixup_subplot([0.2, 0.4, 1.0])

"""# Problem 2"""

class SimpleCNN_Manifold(nn.Module):
    def __init__(self):
        super().__init__()

        # ----- block 1 -----
        self.conv1 = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        # ----- block 2 -----
        self.conv2 = nn.Sequential(
            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        # ----- classifier -----
        self.fc1 = nn.Sequential(
            nn.Linear(64*8*8, 128),
            nn.BatchNorm1d(128),
            nn.ReLU()
        )

        self.fc2 = nn.Linear(128, 10)

    def forward(self, x, mix_layer=None, lam=None, index=None):
        # layer 0: input mix already handled outside

        x = self.conv1(x)
        if mix_layer == 1:
            x = lam * x + (1 - lam) * x[index]

        x = self.conv2(x)
        if mix_layer == 2:
            x = lam * x + (1 - lam) * x[index]

        x = x.view(x.size(0), -1)

        x = self.fc1(x)
        if mix_layer == 3:
            x = lam * x + (1 - lam) * x[index]

        x = self.fc2(x)
        return x

def manifold_mixup_data(x, y, alpha=1.0):
    if alpha > 0:
        lam = Beta(alpha, alpha).sample().item()
    else:
        lam = 1.0

    batch_size = x.size(0)
    index = torch.randperm(batch_size).to(device)

    return x, y, index, lam

def train_manifold(alpha=0.4, epochs=20, mix_layer_choice="random"):
    trainloader, testloader = get_loaders(transform_aug)

    model = SimpleCNN_Manifold().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    train_losses, val_losses = [], []

    for epoch in range(epochs):
        model.train()
        running_loss = 0

        for x, y in trainloader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()

            # choose layer
            if mix_layer_choice == "random":
                mix_layer = random.choice([1, 2, 3])
            else:
                mix_layer = mix_layer_choice

            x, y_a, index, lam = manifold_mixup_data(x, y, alpha)

            outputs = model(x, mix_layer=mix_layer,
                            lam=lam, index=index)

            loss = lam * criterion(outputs, y_a) + \
                   (1 - lam) * criterion(outputs, y_a[index])

            loss.backward()
            optimizer.step()

            running_loss += loss.item()

        train_loss = running_loss / len(trainloader)
        val_loss, val_acc = evaluate(model, testloader, criterion)

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        print(f"MANIFOLD Epoch {epoch+1}/{epochs} "
              f"Loss: {train_loss:.4f} Acc: {val_acc:.2f}%")

    return model, train_losses, val_losses, val_acc

results_manifold = {}

print("=== Random layer ===")
results_manifold["random"] = train_manifold(alpha=0.4)

print("=== Mix at layer 1 ===")
results_manifold["layer1"] = train_manifold(alpha=0.4, mix_layer_choice=1)

print("=== Mix at layer 2 ===")
results_manifold["layer2"] = train_manifold(alpha=0.4, mix_layer_choice=2)

print("=== Mix at layer 3 ===")
results_manifold["layer3"] = train_manifold(alpha=0.4, mix_layer_choice=3)

plt.figure(figsize=(8,5))

for key in results_manifold:
    plt.plot(results_manifold[key][1], label=f"{key} train")
    plt.plot(results_manifold[key][2], '--', label=f"{key} val")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Manifold Mixup Training Curves")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

results_manifold = {}

print("=== Random layer ===")
results_manifold["random"] = train_manifold(alpha=0.2)

print("=== Mix at layer 1 ===")
results_manifold["layer1"] = train_manifold(alpha=0.2, mix_layer_choice=1)

print("=== Mix at layer 2 ===")
results_manifold["layer2"] = train_manifold(alpha=0.2, mix_layer_choice=2)

print("=== Mix at layer 3 ===")
results_manifold["layer3"] = train_manifold(alpha=0.2, mix_layer_choice=3)

plt.figure(figsize=(8,5))

for key in results_manifold:
    plt.plot(results_manifold[key][1], label=f"{key} train")
    plt.plot(results_manifold[key][2], '--', label=f"{key} val")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Manifold Mixup Training Curves")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

from sklearn.manifold import TSNE

def visualize_features(model, loader, num_samples=500):
    model.eval()
    feats, labels = [], []

    with torch.no_grad():
        for x, y in loader:
            x = x.to(device)
            f = model.conv1(x)
            f = model.conv2(f)
            f = f.view(f.size(0), -1)

            feats.append(f.cpu())
            labels.append(y)

            if len(torch.cat(feats)) > num_samples:
                break

    feats = torch.cat(feats)[:num_samples].numpy()
    labels = torch.cat(labels)[:num_samples].numpy()

    tsne = TSNE(n_components=2, random_state=42)
    emb = tsne.fit_transform(feats)

    plt.figure(figsize=(6,5))
    plt.scatter(emb[:,0], emb[:,1], c=labels, s=5)
    plt.title("Feature Space Visualization (t-SNE)")
    plt.show()

model = SimpleCNN_Manifold().to(device)
trainloader, testloader = get_loaders(transform_aug)
visualize_features(model , trainloader)

mixup_logs = {
    0.1: [
        {"epoch": 1, "train_loss": 1.7035, "val_acc": 56.22},
        {"epoch": 2, "train_loss": 1.4178, "val_acc": 62.03},
        {"epoch": 3, "train_loss": 1.2714, "val_acc": 65.56},
        {"epoch": 4, "train_loss": 1.2526, "val_acc": 68.61},
        {"epoch": 5, "train_loss": 1.1685, "val_acc": 69.31},
        {"epoch": 6, "train_loss": 1.1476, "val_acc": 70.91},
        {"epoch": 7, "train_loss": 1.1259, "val_acc": 71.53},
        {"epoch": 8, "train_loss": 1.0694, "val_acc": 71.87},
        {"epoch": 9, "train_loss": 0.9983, "val_acc": 71.33},
        {"epoch": 10, "train_loss": 1.0380, "val_acc": 73.93},
        {"epoch": 11, "train_loss": 1.0037, "val_acc": 73.53},
        {"epoch": 12, "train_loss": 1.0160, "val_acc": 74.21},
        {"epoch": 13, "train_loss": 0.9911, "val_acc": 74.44},
        {"epoch": 14, "train_loss": 0.9516, "val_acc": 74.13},
        {"epoch": 15, "train_loss": 0.9599, "val_acc": 76.31},
        {"epoch": 16, "train_loss": 0.8759, "val_acc": 74.50},
        {"epoch": 17, "train_loss": 0.9945, "val_acc": 76.19},
        {"epoch": 18, "train_loss": 0.9010, "val_acc": 75.87},
        {"epoch": 19, "train_loss": 0.8804, "val_acc": 77.43},
        {"epoch": 20, "train_loss": 0.9383, "val_acc": 75.34},
        {"epoch": 21, "train_loss": 0.9076, "val_acc": 76.49},
        {"epoch": 22, "train_loss": 0.9234, "val_acc": 77.28},
        {"epoch": 23, "train_loss": 0.8781, "val_acc": 78.90},
        {"epoch": 24, "train_loss": 0.8811, "val_acc": 77.67},
        {"epoch": 25, "train_loss": 0.8734, "val_acc": 77.49},
        {"epoch": 26, "train_loss": 0.8425, "val_acc": 78.91},
        {"epoch": 27, "train_loss": 0.9242, "val_acc": 77.92},
        {"epoch": 28, "train_loss": 0.8990, "val_acc": 78.91},
        {"epoch": 29, "train_loss": 0.8912, "val_acc": 77.75},
        {"epoch": 30, "train_loss": 0.8923, "val_acc": 79.14},
    ],

    0.2: [
        {"epoch": 1, "train_loss": 1.7298, "val_acc": 55.84},
        {"epoch": 2, "train_loss": 1.4658, "val_acc": 63.47},
        {"epoch": 3, "train_loss": 1.4212, "val_acc": 65.08},
        {"epoch": 4, "train_loss": 1.3263, "val_acc": 66.71},
        {"epoch": 5, "train_loss": 1.3375, "val_acc": 68.02},
        {"epoch": 6, "train_loss": 1.2157, "val_acc": 68.26},
        {"epoch": 7, "train_loss": 1.2156, "val_acc": 69.30},
        {"epoch": 8, "train_loss": 1.1876, "val_acc": 70.97},
        {"epoch": 9, "train_loss": 1.1719, "val_acc": 71.82},
        {"epoch": 10, "train_loss": 1.2275, "val_acc": 73.53},
        {"epoch": 11, "train_loss": 1.1893, "val_acc": 73.69},
        {"epoch": 12, "train_loss": 1.1021, "val_acc": 74.69},
        {"epoch": 13, "train_loss": 1.1762, "val_acc": 75.08},
        {"epoch": 14, "train_loss": 1.1629, "val_acc": 74.52},
        {"epoch": 15, "train_loss": 1.1015, "val_acc": 75.52},
        {"epoch": 16, "train_loss": 1.1223, "val_acc": 75.76},
        {"epoch": 17, "train_loss": 1.0650, "val_acc": 75.32},
        {"epoch": 18, "train_loss": 1.0464, "val_acc": 76.13},
        {"epoch": 19, "train_loss": 1.0852, "val_acc": 75.75},
        {"epoch": 20, "train_loss": 1.1302, "val_acc": 77.00},
        {"epoch": 21, "train_loss": 1.1211, "val_acc": 76.30},
        {"epoch": 22, "train_loss": 1.0658, "val_acc": 77.74},
        {"epoch": 23, "train_loss": 1.0102, "val_acc": 76.94},
        {"epoch": 24, "train_loss": 1.0887, "val_acc": 77.78},
        {"epoch": 25, "train_loss": 1.0359, "val_acc": 77.89},
        {"epoch": 26, "train_loss": 1.0040, "val_acc": 77.02},
        {"epoch": 27, "train_loss": 1.0499, "val_acc": 78.99},
        {"epoch": 28, "train_loss": 0.9466, "val_acc": 78.97},
        {"epoch": 29, "train_loss": 1.0015, "val_acc": 78.28},
        {"epoch": 30, "train_loss": 0.9798, "val_acc": 79.24},
    ],

    0.4: [
        {"epoch": 1, "train_loss": 1.7994, "val_acc": 52.73},
        {"epoch": 2, "train_loss": 1.5680, "val_acc": 61.69},
        {"epoch": 3, "train_loss": 1.4588, "val_acc": 64.33},
        {"epoch": 4, "train_loss": 1.4724, "val_acc": 66.94},
        {"epoch": 5, "train_loss": 1.4079, "val_acc": 67.39},
        {"epoch": 6, "train_loss": 1.3533, "val_acc": 68.38},
        {"epoch": 7, "train_loss": 1.3675, "val_acc": 70.21},
        {"epoch": 8, "train_loss": 1.3107, "val_acc": 69.90},
        {"epoch": 9, "train_loss": 1.3408, "val_acc": 71.74},
        {"epoch": 10, "train_loss": 1.3933, "val_acc": 69.26},
        {"epoch": 11, "train_loss": 1.3229, "val_acc": 72.35},
        {"epoch": 12, "train_loss": 1.2911, "val_acc": 72.67},
        {"epoch": 13, "train_loss": 1.3432, "val_acc": 73.48},
        {"epoch": 14, "train_loss": 1.2641, "val_acc": 73.46},
        {"epoch": 15, "train_loss": 1.2442, "val_acc": 73.36},
        {"epoch": 16, "train_loss": 1.2653, "val_acc": 74.27},
        {"epoch": 17, "train_loss": 1.2443, "val_acc": 71.93},
        {"epoch": 18, "train_loss": 1.2478, "val_acc": 75.17},
        {"epoch": 19, "train_loss": 1.2259, "val_acc": 75.72},
        {"epoch": 20, "train_loss": 1.2262, "val_acc": 75.33},
        {"epoch": 21, "train_loss": 1.1597, "val_acc": 75.83},
        {"epoch": 22, "train_loss": 1.2178, "val_acc": 75.71},
        {"epoch": 23, "train_loss": 1.2058, "val_acc": 76.48},
        {"epoch": 24, "train_loss": 1.2452, "val_acc": 77.42},
        {"epoch": 25, "train_loss": 1.2335, "val_acc": 76.65},
        {"epoch": 26, "train_loss": 1.2687, "val_acc": 76.87},
        {"epoch": 27, "train_loss": 1.2045, "val_acc": 77.70},
        {"epoch": 28, "train_loss": 1.2341, "val_acc": 76.72},
        {"epoch": 29, "train_loss": 1.2275, "val_acc": 78.35},
        {"epoch": 30, "train_loss": 1.2006, "val_acc": 77.74},
    ],

    0.8: [
        {"epoch": 1, "train_loss": 1.8860, "val_acc": 54.06},
        {"epoch": 2, "train_loss": 1.6811, "val_acc": 59.25},
        {"epoch": 3, "train_loss": 1.6286, "val_acc": 63.35},
        {"epoch": 4, "train_loss": 1.5501, "val_acc": 65.08},
        {"epoch": 5, "train_loss": 1.5307, "val_acc": 62.60},
        {"epoch": 6, "train_loss": 1.5291, "val_acc": 69.74},
        {"epoch": 7, "train_loss": 1.5040, "val_acc": 67.13},
        {"epoch": 8, "train_loss": 1.5072, "val_acc": 69.96},
        {"epoch": 9, "train_loss": 1.5027, "val_acc": 71.75},
        {"epoch": 10, "train_loss": 1.4559, "val_acc": 70.44},
        {"epoch": 11, "train_loss": 1.3822, "val_acc": 72.14},
        {"epoch": 12, "train_loss": 1.4715, "val_acc": 72.57},
        {"epoch": 13, "train_loss": 1.4446, "val_acc": 72.60},
        {"epoch": 14, "train_loss": 1.4864, "val_acc": 73.53},
        {"epoch": 15, "train_loss": 1.4228, "val_acc": 74.35},
        {"epoch": 16, "train_loss": 1.4235, "val_acc": 71.74},
        {"epoch": 17, "train_loss": 1.4464, "val_acc": 74.60},
        {"epoch": 18, "train_loss": 1.3953, "val_acc": 75.40},
        {"epoch": 19, "train_loss": 1.4453, "val_acc": 74.40},
        {"epoch": 20, "train_loss": 1.3847, "val_acc": 75.04},
        {"epoch": 21, "train_loss": 1.4110, "val_acc": 75.56},
        {"epoch": 22, "train_loss": 1.3845, "val_acc": 74.48},
        {"epoch": 23, "train_loss": 1.3825, "val_acc": 74.95},
        {"epoch": 24, "train_loss": 1.3711, "val_acc": 73.89},
        {"epoch": 25, "train_loss": 1.3612, "val_acc": 77.09},
        {"epoch": 26, "train_loss": 1.3638, "val_acc": 76.06},
        {"epoch": 27, "train_loss": 1.3415, "val_acc": 74.64},
        {"epoch": 28, "train_loss": 1.3573, "val_acc": 78.16},
        {"epoch": 29, "train_loss": 1.2963, "val_acc": 78.14},
        {"epoch": 30, "train_loss": 1.3427, "val_acc": 77.11},
    ],
}

import matplotlib.pyplot as plt

# ---- paste your dict above this line ----
# mixup_logs = {...}

plt.figure(figsize=(10, 6))

for alpha, logs in mixup_logs.items():
    epochs = [entry["epoch"] for entry in logs]
    val_accs = [entry["val_acc"] for entry in logs]
    plt.plot(epochs, val_accs, label=f"alpha={alpha}")

plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy (%)")
plt.title("Mixup Alpha vs Validation Accuracy")
plt.legend()
plt.grid(True)

plt.show()

plt.figure(figsize=(10, 6))

for alpha, logs in mixup_logs.items():
    epochs = [entry["epoch"] for entry in logs]
    losses = [entry["train_loss"] for entry in logs]
    plt.plot(epochs, losses, label=f"alpha={alpha}")

plt.xlabel("Epoch")
plt.ylabel("Train Loss")
plt.title("Mixup Alpha vs Train Loss")
plt.legend()
plt.grid(True)

plt.show()

training_logs = {
    "raw": [
        {"epoch": 1, "train_loss": 1.1312, "val_acc": 66.27},
        {"epoch": 2, "train_loss": 0.7922, "val_acc": 67.42},
        {"epoch": 3, "train_loss": 0.6339, "val_acc": 72.29},
        {"epoch": 4, "train_loss": 0.5040, "val_acc": 73.01},
        {"epoch": 5, "train_loss": 0.3933, "val_acc": 72.49},
        {"epoch": 6, "train_loss": 0.2987, "val_acc": 73.23},
        {"epoch": 7, "train_loss": 0.2169, "val_acc": 72.99},
        {"epoch": 8, "train_loss": 0.1540, "val_acc": 72.55},
        {"epoch": 9, "train_loss": 0.1110, "val_acc": 72.84},
        {"epoch": 10, "train_loss": 0.0889, "val_acc": 72.14},
        {"epoch": 11, "train_loss": 0.0749, "val_acc": 73.32},
        {"epoch": 12, "train_loss": 0.0628, "val_acc": 72.52},
        {"epoch": 13, "train_loss": 0.0616, "val_acc": 70.49},
        {"epoch": 14, "train_loss": 0.0596, "val_acc": 73.04},
        {"epoch": 15, "train_loss": 0.0373, "val_acc": 72.53},
        {"epoch": 16, "train_loss": 0.0353, "val_acc": 72.15},
        {"epoch": 17, "train_loss": 0.0442, "val_acc": 71.82},
        {"epoch": 18, "train_loss": 0.0529, "val_acc": 72.54},
        {"epoch": 19, "train_loss": 0.0440, "val_acc": 72.88},
        {"epoch": 20, "train_loss": 0.0285, "val_acc": 73.47},
    ],

    "traditional_aug": [
        {"epoch": 1, "train_loss": 1.4126, "val_acc": 63.27},
        {"epoch": 2, "train_loss": 1.1038, "val_acc": 67.50},
        {"epoch": 3, "train_loss": 0.9992, "val_acc": 67.25},
        {"epoch": 4, "train_loss": 0.9300, "val_acc": 71.88},
        {"epoch": 5, "train_loss": 0.8798, "val_acc": 73.99},
        {"epoch": 6, "train_loss": 0.8394, "val_acc": 73.54},
        {"epoch": 7, "train_loss": 0.8065, "val_acc": 76.04},
        {"epoch": 8, "train_loss": 0.7757, "val_acc": 74.84},
        {"epoch": 9, "train_loss": 0.7525, "val_acc": 76.38},
        {"epoch": 10, "train_loss": 0.7368, "val_acc": 75.74},
        {"epoch": 11, "train_loss": 0.7139, "val_acc": 75.36},
        {"epoch": 12, "train_loss": 0.6984, "val_acc": 76.56},
        {"epoch": 13, "train_loss": 0.6793, "val_acc": 77.46},
        {"epoch": 14, "train_loss": 0.6704, "val_acc": 77.86},
        {"epoch": 15, "train_loss": 0.6576, "val_acc": 79.47},
        {"epoch": 16, "train_loss": 0.6454, "val_acc": 79.11},
        {"epoch": 17, "train_loss": 0.6382, "val_acc": 77.69},
        {"epoch": 18, "train_loss": 0.6314, "val_acc": 80.04},
        {"epoch": 19, "train_loss": 0.6168, "val_acc": 79.24},
        {"epoch": 20, "train_loss": 0.6070, "val_acc": 79.91},
    ],

    "mixup_alpha_0.4": [
        {"epoch": 1, "train_loss": 1.6990, "val_acc": 62.21},
        {"epoch": 2, "train_loss": 1.4817, "val_acc": 66.63},
        {"epoch": 3, "train_loss": 1.4319, "val_acc": 67.58},
        {"epoch": 4, "train_loss": 1.3900, "val_acc": 67.48},
        {"epoch": 5, "train_loss": 1.3648, "val_acc": 71.02},
        {"epoch": 6, "train_loss": 1.3279, "val_acc": 71.86},
        {"epoch": 7, "train_loss": 1.3371, "val_acc": 73.16},
        {"epoch": 8, "train_loss": 1.2827, "val_acc": 74.62},
        {"epoch": 9, "train_loss": 1.2759, "val_acc": 75.59},
        {"epoch": 10, "train_loss": 1.2694, "val_acc": 74.42},
        {"epoch": 11, "train_loss": 1.2038, "val_acc": 74.44},
        {"epoch": 12, "train_loss": 1.2143, "val_acc": 76.50},
        {"epoch": 13, "train_loss": 1.2189, "val_acc": 77.34},
        {"epoch": 14, "train_loss": 1.2270, "val_acc": 77.16},
        {"epoch": 15, "train_loss": 1.2467, "val_acc": 77.37},
        {"epoch": 16, "train_loss": 1.1855, "val_acc": 77.76},
        {"epoch": 17, "train_loss": 1.1873, "val_acc": 78.56},
        {"epoch": 18, "train_loss": 1.1659, "val_acc": 77.13},
        {"epoch": 19, "train_loss": 1.1621, "val_acc": 78.68},
        {"epoch": 20, "train_loss": 1.1844, "val_acc": 78.36},
    ],
}

import matplotlib.pyplot as plt

# ---- paste your training_logs dict above this line ----

plt.figure(figsize=(10, 6))

for method, logs in training_logs.items():
    epochs = [x["epoch"] for x in logs]
    val_acc = [x["val_acc"] for x in logs]
    plt.plot(epochs, val_acc, label=method)

plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy (%)")
plt.title("Training Strategy Comparison")
plt.legend()
plt.grid(True)

plt.show()


plt.figure(figsize=(10, 6))

for method, logs in training_logs.items():
    epochs = [x["epoch"] for x in logs]
    losses = [x["train_loss"] for x in logs]
    plt.plot(epochs, losses, label=method)

plt.xlabel("Epoch")
plt.ylabel("Train Loss")
plt.title("Train Loss Comparison")
plt.legend()
plt.grid(True)

plt.show()

